- src/repository.ts
Currently the tree view in the source control section shows the absolute path of the repository:
This PR fixes that by giving the repository root to the vscode, so it can strip it from the paths. But then I found out that it only works for the working copy and not parents, due parents using `jj` scheme, and vscode doesn't like that. I removed the `jj` scheme, which is probably wrong, but I wasn't sure what to do so I just submitted the patch to get feedback.
> Fix showing absolute path in source control tree view

- src/decorationProvider.ts
- src/repository.ts
- src/uri.ts
This PR fixes missing decorations in file explorer, which is probably regressed in https://github.com/keanemind/jjk/commit/d08911f517cddc57e15317a7f634297c4c596d26 , and adds support for graying out ignored files. ~I didn't find out how to ask tracked/ignored files list from jj, so current implementation is git based and not absolutely correct (e.g. it doesn't handle explicitly tracked files), and it is not auto updated, but I think it is still better than nothing.~ I found that there is a `jj file list` that lists the tracked files, and I used that.
> Show ignored files in gray

- .gitignore
These dirs appeared when I ran `npm test`.
I also wonder whether the `src/**/*.js` .gitignore is necessary, since all the js files seem to go into `out/`, at least in my experience.
> .gitignore: add out/ and .vscode-test/

- src/repository.ts
When operating on a single change, jj show is equivalent to jj log except it always appends the diff to the end of the output.
jj show was generating and appending the full diff after the template fields, and since I had a custom diff tool configured that ran fairly slowly, it was causing the command to timeout.
Since the extension isn't even reading the diff, it's better to switch to jj log to avoid generating the diff.
To show some sample equivalent commands:
These two commands are equivalent:
- `jj log --no-graph -T 'change_id ++ " ==> " ++ diff.summary()' -r @`
- `jj show --summary -T 'change_id ++ " => "' @`
These two commands are also equivalent:
- `jj log --no-graph -T 'change_id ++ " ==> " ++ diff.git()' -r @`
- `jj show --git -T 'change_id ++ " => "' @`
> Use jj log instead of show

- src/main.ts
Fixes https://github.com/keanemind/jjk/issues/9
> Update blame decoration when text is edited to keep it at the end of the line

- src/repository.ts
`jj log` will just have no output if the revision doesn't exist (e.g., `zzzzzzzz-`)
> Update hardcoded error check now that we use `jj log` instead of `jj show`

- package.json
Think this was accidentally introduced by a messed up rebase in #40
> Remove command that doesn't exist

- src/logger.ts
- src/main.ts
We're currently missing the logs from the call to jj version because it happens before log initialization, so I moved that down. We also should capture all log levels; users can filter the output channel by log level for display.
> Capture more logs

- .gitignore
This tells tooling that's not jj aware but that does respect `.gitignore` to avoid looking into the `.jj` folder
> add .jj to .gitignore

- src/repository.ts
The race condition is in `refreshUnsafe`, where it calls `jj status` and then calls `jj log -r` on each parent change that it saw in status. If a parent change no longer exists (because of a squash or other operation that happened in between) by the time the `jj log -r` call is made, the `jj log -r` call fails. This is normal and ok because we'll just try again at the next refresh attempt. However, the root problem was that the way I set up the promise handling, once the promise was rejected, it would stay rejected forever.
> Fix unrecoverable error loop when race condition is encountered

- package-lock.json
- package.json
- src/repository.ts
Previously we were including `(empty)` and `(conflict)` in the parsed description, leading to us presenting that as the description in things like the source control view and the description input that comes up when squashing. The way we distinguish the (empty) and (conflict) from those strings being in the change's description itself is using the ANSI sequences now, so we have to pass `--color=always` to `jj status`. 
Also, when multiple bookmarks were on the same change, it would break the regex and cause the parsed description to include the bookmarks, pipe character, and change description.
> Fix edge cases with parsing `jj status` output

- src/fakeeditor/src/main.zig
When `jj` receives a `SIGTERM`, I've noticed that it doesn't kill the fakeeditor process that it spawned, leaving the fakeeditor process behind running forever. This PR makes it so that fakeeditor won't keep running forever in those situations.
> Make fakeeditor exit after 5 seconds

- package-lock.json
- package.json
- src/uri.ts
- tsconfig.json
Rather than specifying a file at a certain rev, this new kind of URI specifies a file _on the left side of the diff for the specified rev_. In practice "the left side of the diff for the specified rev" will either be a parent rev if there's only one parent, or the merge of all parent revs if there are multiple parents. The merge of all parent revs is not itself a rev, and yet the URI specifies a file in that merged state. I chose to make this a new kind of URI with a field that's named something other than `rev` to try to force our uses of these URIs to confront that distinction.
> Add `diffOriginalRev` field to JJUriParams

- src/decorationProvider.ts
- src/fileSystemProvider.ts
- src/main.ts
- src/repository.ts
- src/uri.ts
Every place that uses URIs now needs to check whether the URI refers to a specific rev, or if it refers to the left side of a diff and handle those cases accordingly.
This feature uses the fakeeditor we've recently introduced by passing it to `jj diff`.
> Implement diff for merge commits

- src/repository.ts
`fs.cp` when copying a directory doesn't delete extra files in the destination, so we delete the whole destination first.
> Fix squash selected changes bug where newly added files would be squashed

- src/repository.ts
Since we delete the right folder, just to be extra safe, do extra validation of the fakeeditor output to make sure things are working as expected.
> Check folder names in squashContent for extra safety

- src/repository.ts
Since the diff does not update when you move the working copy around, I think just having the change id in the title is less confusing and will make it clearer why the diff doesn't update.
> Change title of parent resource states to be the changeId instead of "(Parent Change)"

- languages/jj-commit.language-configuration.json
- package.json
- syntaxes/jj-commit.tmLanguage.json
This adds a language and grammar for `.jjdescription` files which allows for proper syntax highlighting of the `JJ:` comments, as well as the added/modified/deleted files. 
Adapted from VSCode's [git-base](https://github.com/microsoft/vscode/tree/296e736cd51c18cf5899662566cea384aa0550e0/extensions/git-base) extension for `git-commit`/`COMMIT_EDITMSG`
Screenshot of this commits description
> add language/grammar for .jjdescription

- package.json
- src/main.ts
- src/repository.ts
This adds a new button on the top left of the editor. If the current editor is a diff editor, then the button will take you to the file for the right side of the diff. If the current editor is not a diff editor, then the button will take you to the diff between the current editor's URI and its original resource.
> Add commands to switch between file and diff

- package.json
Commands Hidden:
- jj.openFileResourceState
- jj.openFileEditor
- jj.openDiffEditor
- jj.describe
- jj.squashToParentResourceGroup
- jj.squashToWorkingCopyResourceGroup
- jj.squashToParentResourceState
- jj.squashToWorkingCopyResourceState
- jj.editResourceGroup
- jj.restoreResourceState
- jj.restoreResourceGroup
- jj.selectOperationLogRepo
- jj.operationRestore
- jj.selectGraphWebviewRepo
- jj.placeholderForFolders
- jj.openParentChange
- jj.openChildChange
- +jj.operationUndo
Remaining Commands:
- jj.refresh
- jj.new
- jj.gitFetch
- jj.refreshOperationLog
- ~jj.operationUndo~
- jj.refreshGraphWebview
- jj.newGraphWebview
- jj.squashSelectedRanges
> Hide incompatible commands from the command palette

- src/fakeeditor/src/main.zig
- src/repository.ts
This will abort the squash operation. If we don't abort the squash operation and the `right` folder is unmodified, everything will get squashed, which is bad.
> Ensure fakeeditor exits with a non-zero exit code unless the `right` folder is fully prepped

- src/fakeeditor/src/main.zig
- src/repository.ts
This should fix the intermittent "Unexpected output from fakeeditor" errors that I've been seeing. I think the cause was that I wasn't properly handling the possibility where the output comes in from two different "data" events.
> Use end of output sentinel from fakeeditor

- src/main.ts
Before this PR, if you start off in diff view, move to a child change, then switch to file view, the tab will be missing the rev in its title.
> Fix tab name when switching from diff to file view

- src/repository.ts
Related to https://github.com/keanemind/jjk/commit/6d57db151ad06813edb3883b7d2e38c9a19f9675. All filepaths that go to jj must be made relative to avoid introducing colons on Windows, because in Windows absolute paths, drive letters are followed by colons.
> Pass relative filepath to jj in `getDiffOriginal`

- src/repository.ts
The [TOML spec](https://toml.io/en/v1.0.0#string) says only
> quotation mark, backslash, and the control characters other than tab (U+0000 to U+0008, U+000A to U+001F, U+007F)
need to be escaped. I think of those, only backslashes can appear in filepaths (on Windows).
> Escape backslashes in TOML passed to `jj squash`

- src/repository.ts
This allows us to support filepaths with colons in them, wherever the colons are. Previously we were using relative paths to avoid the colons following the drive letter on Windows, but https://github.com/keanemind/jjk/issues/83 shows that a colon could be anywhere in the path. 
Thank you @lishaduck for pointing out this aspect of filesets to me
> Convert filepaths to filesets with the "file" pattern, rather than passing jj relative paths

- src/fakeeditor/src/main.zig
- src/repository.ts
The previous iteration of fakeeditor relied on POSIX signals to know whether it should exit with code 0 or not. That mechanism of communication didn't seem to work properly on Windows. We're now moving to using named pipes with more OS-specific code to communicate.
> Fix fakeeditor for Windows

- src/repository.ts
```
ReferenceError: can't access lexical declaration 'output' before initialization
```
The error is thrown synchronously and we don't catch it so we never reject nor resolve the promise. Also made some error handling more consistent between `getDiffOriginal` and `squashContent`.
> Fix `ReferenceError` that was leading to hanging in `getDiffOriginal`

- package.json
`scmProvider == jj` is only true when you actively have the source control view open.
> Fix command when clauses to use `jj.reposExist` instead of `scmProvider == jj`

- src/main.ts
- src/repository.ts
Currently, restoring a renamed file via jjk's file restore command will simply delete the file, without putting it back with its previous name. This fixes that by passing both the old and new filenames to `jj restore`.
> Fix restore of renamed files

- src/fileSystemProvider.ts
- src/graphWebview.ts
- src/main.ts
- src/operationLogTreeView.ts
- src/repository.ts
This makes jjk much more responsive to repository updates that happened outside of jjk, such as from the command line.
> Watch operation log to replace all polling except for one command used for snapshotting

- src/main.ts
- src/repository.ts
This issue has always existed but is easier to encounter now after https://github.com/keanemind/jjk/pull/132
> Quick fix for operation log and graph view holding onto stale repository instances

- package.json
Fix #84
Turns out that VSCode has a really easy way to achieve this.
Preview of what the settings look like with this change
> Add a files exclusion setting for .jj

- src/webview/graph.html
Fix #140
This makes sure that any jj description will only ever be rendered as text, and never be interpreted specially.
e.g.
> Fix rendering descriptions with html entities

- src/repository.ts
Currently, workspaces containing folders within the same repository cause the aforementioned repository to occur multiple times in the `Source Control`view.
Changes made in this PR fix this by memorizing the `fsPath` of each repository and ensuring it's only added once.
Changes made in this PR will fix #147
> Prevent Duplicate Repositories
